### ISSUE TITLE
SessionPlugin doesn't seem to output MMR data to CSV

### ISSUE THREAD

**Issue by jacksonmeyn** [MeineZ/BMSessionPlugin#4]
The SessionPlugin folder where the MMR CSV is supposed to save doesn't seem to get created, even though the box is ticked in plugin settings in RL. I'm a new user of SessionPlugin so I'm not sure how it worked before, but I'm guessing it might have something to do with the fact that bakkesmod now keeps its files in %appdata%/bakkesmod since the Epic Games compatibility update. (https://bakkesmod.fandom.com/wiki/Troubleshooting#Epic_Games_version_of_rocket_league)

Hopefully it's a simple fix. I'd offer to do it myself and submit a pull request but I don't have much experience with C++

**Comment by MeineZ** [comment]
Hey! Thank you very much for reaching out! I thought I had adapted to this update already, but this doesn't appear to be working indeed.

I will look at it asap and will keep you up-to-date!

**Comment by MeineZ** [comment]
It should now work again! It may take a while to be accepted by the BakkesMod staff, but it'll automatically update when it is :)

Please let me know if the latest update fixed it! :D

**Comment by jacksonmeyn** [comment]
Thanks! I'll let you know

**Comment by jacksonmeyn** [comment]
Hey, it became available through bakkesplugins today. I completely removed it and reinstalled the plugin but still can't see the sessionplugin folder or any CSVs in appdata/bakkesmod/data. It's version 1.9 right?

Thanks again

**Comment by MeineZ** [comment]
That's weird... Yeah, it's version 1.9. Have you checked `AppData/bakkesmod/bakkesmod/data/SessionPlugin`? Or only the data folder?
Sorry for the trouble.

**Comment by jacksonmeyn** [comment]
Yes sorry that’s the path I meant. Can’t see the SessionPlugin folder at
that path. I might post in the bakkesmod subreddit to make sure it’s not
just me for some reason.

Thanks again

**Comment by MeineZ** [comment]
That's odd.. Are you playing RL on Epic Games? Perhaps that has something to do with it? I will look at it when I can find the time :)

**Comment by jacksonmeyn** [comment]
I tried creating the SessionPlugin folder manually and the CSVs were created after that!

The only other thing I'm wondering now is if it's possible to include MMR change of all players in the CSV instead of just myself, but I'll close this ticket and open a new one for that.

Cheers
